### PR TITLE
Added Friendmoji render URL

### PR DESCRIPTION
**Pull request by willdavidow**
- Adds function to build friendmoji's; requires two avatar ID's (both can be the same)
- Adjust how template data is pulled in (split `friends` and `imoji` objects into their own variables)

### CODE REVIEW

**Comment by lights0123** [comment]
Should documentation also be added for finding other people’s IDs by using mitmproxy and Snapchat?

**Comment by willdavidow** [comment]
If you have the details on how to do those things that'd be pretty handy...

**Comment by willdavidow** [comment]
but it seems complicated... 

Upon further investigation around mitmproxy + the iOS version of Snapchat (I don't have an Android device to test)... I actually don't think this method works (if it ever did/anymore?) because SC has implemented certificate pinning. Seems like the juice isn't worth the squeeze at that point, since you'd have to decompile the app and do a bunch of other hoop-jumping just to step around that.. 

I'd rather just point people to the docs in this repo on finding their ID's by logging in, or step them through it myself... if there's a more simple way to do it I'm all-ears, but mitmproxy and app decompilation seems outside the realm of feasibility for most people.

**Comment by willdavidow** [comment]
Ah, so the idea is that you’re able to use SC with out being blocked from the app using their endpoints from the proxy...

...and then you just send a friend a friendmoji and you’ve got a render url string with your and their user id?

That’s pretty clever.

**Comment by lights0123** [comment]
Don’t even have to send it, just open the Bitmoji tab.

**Comment by willdavidow** [comment]
@lights0123 Having a little trouble connecting to SnapChat once I run `mitmproxy --ignore-servers snapchat.com`. After I run that, I added a manual proxy on my iPhone network connection back to my computer running mitmproxy - I'm able to see network traffic coming out of Safari (from my iPhone), but I did have to make a security exception first before it let me access the site... but when I open up Snapchat I can't refresh the feed, and clicking into the bitmoji keyboard just results in a bunch of `!` indicating nothing loaded.

Full disclosure: this is the first time I've used mitmproxy, and I'm almost certain I'm doing something wrong and/or blocking the wrong server.

Does the way I've set it up sound about right, or is there more to it - maybe different servers?

**Comment by lights0123** [comment]
I used `mitmweb --ignore-hosts '.*(snapchat\.com|\.net|feelinsonice\.com|snapads\.com).*'` as my command (`mitmweb` is installed also, just gives you an easy, browser-based version). With mitmproxy, you need to go to `mitm.it` on the target device to install a root SSL certificate. Also, I had trouble (although it might have just been me) with a regular HTTP proxy, I had to add `--mode transparent --showhost` and ARP spoof my phone.

**Comment by lights0123** [comment]
There's also a batch API that the app calls with a bunch of comic IDs, which would be an interesting thing to add to libmoji.

**Comment by willdavidow** [comment]
Seems like this could be pretty cool, but I feel like `mitmproxy`/`mitmweb` / `Charles` are all a little outside the scope of this pull request.  I'm happy to try any steps you can come up with for documentation, and because I'm genuinely curious... but I'm not able to ARP spoof my phone since it's not jailbroken. 

With Charles Proxy, I saw a few calls to `api.bitmoji.com`:
screen shot 2018-07-11 at 10 37 27 pm
but they all produced bad response data, and ultimately nothing useful.

@matthewnau not sure how you feel about the documentation/steps to get folks' user id's that @lights0123 is suggesting, but it feels a little outside the scope of this PR to me.. your call though!

**Comment by matthewnau** [comment]
@willdavidow when I did my initial reverse engineering for Libmoji, I had to set up a certificate for Charles in order to get data since Bitmoji employs SSL pinning on their app. Try following the steps [here](https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/) for iOS and you may be able to return good data. Also, @lights0123 I'll look over this pull request in the next few days 👍

**Comment by lights0123** [comment]
> but I'm not able to ARP spoof my phone since it's not jailbroken

ARP spoofing can be done from any computer on the LAN. It just tells the device that the computer is the router, and the router is the computer. On Mac, you can download [this](https://github.com/ivanvza/arpy) and run `sudo arpy -t 192.168.phone.address  -i en1 --sniff > /dev/null` (replacing `en1` with your interface). On Linux, install `arpspoof` ("`dsniff`" package in your package manager) and run `sudo arpspoof 192.168.phone.address -t 192.168.router.address` *and* `sudo arpspoof 192.168.router.address -t 192.168.phone.address`. I don't use Windows that often, so I don't know of a native solution.

But anyways, I'll see what @matthewnau thinks about this (if it's too privacy invading to get other people's bitmoji IDs) and transfer to a new issue.

**Comment by willdavidow** [comment]
@lights0123 thanks for the steps, definitely helpful - I ended up installing ettercap with homebrew and that proved to be what made things work here..

@matthewnau - thanks for the link. I had completed all the steps listed on that page, but still no luck... until I installed ettercap (`brew install ettercap --with-gtk+`) and fired up a 'unified sniffing session`..

Getting good data now, but I'm noticing that the images being served back come from `images.bitmoji.com`, however in my pull request I used the `render.bitstrips.com` url that is in use for `baseCpanelUrl`.. There doesn't appear to be any difference in what's returned between the two when appending the path after each domain.

**Comment by matthewnau** [comment]
@lights0123 and @willdavidow I've decided to approve this pull request. I think the use of friendmojis is a nice feature and a good option for users of Libmoji to have access to. I also agree that the additional steps given to get a friendmoji's user id may be a gray area. I think the documentation should be provided (I will make a page in the wiki), but should include a warning or discretionary notice. When you get a chance, email me your steps/documentation of getting a friendmoji and I'll put it up. Thanks guys, awesome work 😃

**Pull request merged**
